### ISSUE TITLE
Maven Central?

### ISSUE THREAD

**Issue by mplatvoet** [kittinunf/Fuel#11]
Any plans to release this to Maven Central? That way I can write some [Kovenant](http://kovenant.komponents.nl) extensions for this.

**Comment by kittinunf** [comment]
@mplatvoet, that is awesome. Thank you so much for considering my lib is useful. Yeah I would find some time to work on this, I'll let you know as soon as it is done.

**Comment by mplatvoet** [comment]
Great, looking forward to it

**Comment by kittinunf** [comment]
Please hang on tight. Maven Central doesn't allow me to use `fuel:fuel` for artifactID. They ask me whether I own the domain name `fuel` which I certainly don't. This makes me go for another option on MavenCentral such as `com.github.kittinunf:fuel` which I don't like because usage for JCenter and MavenCentral will be different.  :cry:

**Comment by mplatvoet** [comment]
Jcenter will do find too, as long as it's online available I guess. And maybe it makes more sense to add some extensions under your project?

**Comment by kittinunf** [comment]
It is already available on JCenter I think. Are you having some problem syncing with JCenter with Fuel?

**Comment by gildor** [comment]
@kittinunf I believe this feature must be reopened. Artifact id is not a problem anymore, it already com.github.kittinunf.fuel
Not every project uses JCenter (which has a lot less strict policies, which just not allowed), one more reason is the usage of Kotlin scripting. Fuel would be very helpful there because it simple to use, but [Kotlin Main Script](https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/#scripting) by default uses maven central 
Because you already publishing to JCenter, you can republish to Maven Central, it supported by JCenter

**Comment by kittinunf** [comment]
Sure! Thanks for reporting on this and for your suggestions! I will try to see whether it can be done quickly.
