### ISSUE TITLE
RxJava 2.x support

### ISSUE THREAD

**Issue by mradzinski** [kittinunf/Fuel#130]
Any plans to update Fuel so it can support RxJava 2.x?

**Comment by kittinunf** [comment]
Yes. It will be supported in next release!

**Comment by VictorAlbertos** [comment]
@kittinunf :), if you want I can create another module, called fuel-rxjava2, with the same structure that the module for rxjava1.

**Comment by kittinunf** [comment]
@VictorAlbertos I planned to just replace the current RxJava module with 2.x altogether. I honestly don't really want to maintain 2 RxJava modules. What do you think?

**Comment by VictorAlbertos** [comment]
I agree. I think you should not maintain Rx1 version any longer. At least, that's the way most of the android dev are doing it nowadays. But, still, maybe it would be a good idea keeping Rx1 module, and creating a new one for Rx2. I said so because, so far, every library out there is doing that, either it creates a new branch, a new repo or new module. But, of course, that question is entirely up to you :) Whatever you choose, the important thing is that you should not provide maintenance for rx1 version, because it's a way to promote the migration from 1 to 2 version in the long run :)

**Comment by kittinunf** [comment]
I think I wanna go with replacing RxJava1 to 2 entirely. Thanks! @VictorAlbertos thanks for your discussion/suggestion.
