### ISSUE TITLE
Non Android support

### ISSUE THREAD

**Issue by yoavst** [kittinunf/Fuel#18]
Is it planned? Currently it requires to use robolectric to test api calls.
From a quick view (running without roboelectric) you use android's Uri class. Is there any alternative?

**Comment by kittinunf** [comment]
Yes, originally, it was created just to serve my client with Android development. So that I decided to make it to be an Android lib. Because I just need a quick solution on it. 

Definitely, it can be generalized to be a Kotlin lib because in general, it should serve as a pure HTTP Client lib without Android dependency.

I think I should split this into multiple modules.

fuel
fuel-android 

Do you think it is good? If yes I will find some time to work on it.
