### ISSUE TITLE
rxjava : use onError for the errors

### ISSUE THREAD

**Issue by fabienmoritz** [kittinunf/Fuel#202]
Hi, thanks for this great lib !

In RxFuel, why don't we put the FuelError in the `onError` emitter instead of putting everything in `onSuccess` ? We could simplify the signatures this way by getting rid of the Result class.

I am a beginner on rxjava, but I could make a PR if you like.

**Comment by yoavst** [comment]
Good question indeed. @kittinunf , any idea?

**Comment by kittinunf** [comment]
This is intentional by design. Having emitting as `onError` will cut down the stream. If upstream was tied to the UI, where the stream is infinite will terminate the whole chain. To solve that user needs to do some sort of operator to recover this such as `onErrorReturn` or something similar. 

I think the current way is more suitable.
