### ISSUE TITLE
Using fuel with Orbot

### ISSUE THREAD

**Issue by transifex3** [kittinunf/Fuel#209]
Hi Developers!

I'm really new to java and kotlin world, so please be patients if i am asking you really basic question.

What i need is to use Fuel with Orbot, http proxy or socks5 proxy, without configuring any system-wide settings in Android.
(Like Network - WIFI - Proxy .... in Setting)

So i tried to lookup some code snippets including "proxy" word, but it made noting sense to me.

Any suggestions or way to through it? It will be glad to get some information from senior developers. Thank you :D

**Comment by yoavst** [comment]
You can configure proxy to `FuelManager` - https://github.com/kittinunf/Fuel/blob/8788ea10475ccf37a07988ead49ec7bb7bd18857/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/FuelManager.kt#L23
However, after the first request You'll have to call also
`FuelManager.client =  HttpClient(proxy)`

**Comment by transifex3** [comment]
Thank you @yoavst !!
Finally i got some working things in my editor 👍 

I hope you can teach me some other things..
Is it possible to change user-agent string too?
and any particular reason that you have to call `FuelManager.client = HttpClient(proxy)`?
(Because It worked without code above several times)

Here is what i did in my editor

```
fun test() {
        doAsync {
            //if we set baseURL beforehand, simply use relativePath
            FuelManager.instance.basePath = "http://httpbin.org"

            var addr: InetSocketAddress = InetSocketAddress("localhost", 9050)

            FuelManager.instance.proxy = Proxy(Proxy.Type.SOCKS, addr)
            "/get".httpGet().responseString { request, response, result ->
                //make a GET to http://httpbin.org/get and do something with response
                val (data, error) = result
                if (error != null) {
                    toast("Failed!!")
                } else {
                    toast("Success!!")
                }
            }
        }
    }
```

**Comment by yoavst** [comment]
Line 22 is: `var client: Client by readWriteLazy { HttpClient(proxy) }`, meaning after the first request you can't change the proxy without changing the client. Perhaps we need to make it a getter instead of lazy. What do you think @kittinunf ?

~~About user-agent. You have to set it on the `HTTPUrlConnection`, as specified [here](https://stackoverflow.com/a/9828691/4874829). However you don't have access to the `HTTPUrlConnection`, which is used [here](https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt#L23).~~

You just have to add an header to the request. You can add headers to all requests as specified [here](https://github.com/kittinunf/Fuel/tree/master#configuration):
`FuelManager.instance.baseHeaders = mapOf("Device" to "Android")`
Or to a single request using one of those two methods on `Request` class (you get it from `httpGet()`):
```kotlin
fun header(vararg pairs: Pair<String, Any>?): Request
fun header(pairs: Map<String, Any>?): Request
```

**Comment by transifex3** [comment]
So it's not necessary to call `FuelManager.client = HttpClient(proxy)` when i don't need to change the proxy right?
For user-agent, changing device header did not worked to me, so i changed header to "User-Agent" one.
`FuelManager.instance.baseHeaders = mapOf("User-Agent" to "Censored")` and it seems works now!
 thanks for your kind, and making this awesome project @yoavst 😄
It's really make beginners happy to dig with codes!

**Comment by yoavst** [comment]
Not, it is not necessary. 
Keeping it open for @kittinunf  to answer this:

> Line 22 is: var client: Client by readWriteLazy { HttpClient(proxy) }, meaning after the first request you can't change the proxy without changing the client. Perhaps we need to make it a getter instead of lazy. What do you think @kittinunf ?

**Comment by kittinunf** [comment]
I think I use `readWriteLazy` for a reason, unless I should have used just regular `lazy`. In other words, this means that you should be able to set value, freely. But if you haven't set, it uses `HttpClient(proxy)` as the default.

**Comment by yoavst** [comment]
Yes, but In case `proxy` field change, it will not update the client. Maybe we should pass `() -> Proxy` instead and it will call `FuelManager.proxy`?

**Comment by yoavst** [comment]
Closing this as our discuss is out of the scope of the question
