### ISSUE TITLE
[Android] Run callback on caller / background thread

### ISSUE THREAD

**Issue by wdullaer** [kittinunf/Fuel#361]
Would it be possible to add an option to disable the `runOnUiThread` behaviour?
I have a usecase where I need to fetch some data over HTTP from an IntentService, which runs on a background thread. Most of the logic is in the fuel callback, and that should preferably also run on the background thread.
I'm making do with wrapping stuff in `thread {}`now, but it would be nice to have the option in this library.

**Comment by kittinunf** [comment]
I think the Callback style was design with the ease-of-use in mind so that there was no configuration support from the beginning. 

Can you try the synchronous version instead? If you use the synchronous version, it will just run on the caller thread hence in your use-case, it will be on the bg thread?

**Comment by wdullaer** [comment]
I think the default behaviour is great. It does what you expect it to in 90% of the cases.
The sync option is a good tip. My calls can run on both the UI and a backend thread though, depending on the context.
I suppose wrapping the callback in thread on these cases is not the end of the world.

**Comment by kittinunf** [comment]
Ok closing this issue then
