### ISSUE TITLE
Socks5 proxy auth

### ISSUE THREAD

**Issue by kolayv** [kittinunf/fuel#419]
How i can use socks5 proxy with login and password in fuel? Im using java.net.Proxy, but it have`nt login and password fields

**Comment by SleeplessByte** [comment]
FYI, if you are trying this on Android, please note that this only works on Marshmellow and above.

The only way to use Proxies with Fuel is by using `java.net.Proxy` and passing it to `FuelManager`

```Kotlin
val proxyAddr = InetSocketAddress(proxyHost, proxyPort);
val proxy = Proxy(Proxy.Type.SOCKS, proxyAddr);

FuelManager.instance.proxy = proxy
```

Since `java.net.Proxy` is not a part of `Fuel`, we can not make changes on how to interact with that Class. You can probably set the system wide authenticator using `Authenticator`, but to override how the connection is build, you'll need to implement your own `HttpClient`.
