### ISSUE TITLE
POST Request break between 1.14.0 and 1.15.0 

### ISSUE THREAD

**Issue by alexpwf** [kittinunf/Fuel#469]
# Bug Report

## Description
The body parameter seems to no longer work in the new version.

## To Reproduce
For the same code, the body gives different results.

```Kotlin
val data = JSONObject()
data.put("email", "e@m.c")
data.put("password", "pwd")
 
// send the HTTP request
Fuel.post(URL)
    .header("Content-Type" to "application/json")
    .body(data.toString())
    .response { _, _, result ->
               /* ... */
    }
```
In the 1.14.0 server receive `{"email":"e@m.c","password":"pwd"}`
In the 1.15.0 server receive `{ '{"email":"e@m.c","password":"pwd"}': '' }`

**Comment by mgee** [comment]
The post function automatically adds a `Content-Type=application/x-www-form-urlencoded` header.
Before Fuel 1.15.0 the `header` function overload taking a variable number of pairs overwrote existing headers.
This function overload was changed to append to existing values instead.
The content type header in the example is now:
`Content-Type=application/x-www-form-urlencoded; application/json`.

Your example will behave like before if you use the `header` overload which takes a map because it always replaces existing values:
```kotlin
Fuel.post(URL)
    .header(mapOf("Content-Type" to "application/json"))
    .body(data.toString())
    .response { _, _, result ->
               /* ... */
    }
```

**Comment by alexpwf** [comment]
That work, thank you, guys!
