### ISSUE TITLE
jsonBody does not replace default content encoding

### ISSUE THREAD

**Issue by NikkyAI** [kittinunf/Fuel#473]
# Bug Report

## Description
when POST-ing a json body the generated request contains both of these headers
```
Content-Type : application/x-www-form-urlencoded
content-type : application/json
```

because of https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt#L149

## To Reproduce

```Kotlin
val curl = Fuel.post("https://someurl.com")
            .jsonBody(body = "{}")
            .cUrlString()
println(curl)
```

## Expected behavior
the POST request should have only one Content-Type

**Comment by SleeplessByte** [comment]
Correct. @markGilchrist I want to change the behaviour so that:
- headers that only allow one value (things like Date, Content-Type, Content-Language, Expires) don't concat
- defaults set by us are either "only set if not already set" or "always overwritten when the header is processed/used/changed"

**Comment by NikkyAI** [comment]
for now #474 fixes it without a complete rewrite of headers, but it would break if somone sets a Content type and then calls jsonBody
but it should be obvious to users that it will break

**Comment by mgee** [comment]
This is the same issue as #472.
