### ISSUE TITLE
connection.headerFields must not be null

### ISSUE THREAD

**Issue by xdma** [kittinunf/Fuel#482]
I get an error only in android 4,  "java.lang.IllegalStateException: connection.headerFields must not be null", in other android versions everything works fine, maybe someone faced with similar issue?

**my request code:** 

` val request = url.httpGet()`
`request.timeout(timeout * 1000)`
` .timeoutRead(readTimeout * 1000)`
`.header(mapOf(`
`                    "token" to "xxx",`
`                    "content-type" to "application/json"))`
`                .responseJson { request, response, result ->`
`                    result.fold(success = {`
`...`
`                    }, failure = {`
`...`
`                    })`
`                }`

**Comment by SleeplessByte** [comment]
There are multiple issues with the `headerFields` type definition, on the Android side, which might or might not have anything to do with this and might or might not be [partially] fixed by #481.

However, because we are running into multiple issues with Android 4.4 and lower, the minSDK is actually being raised per #483 to Android 5.0. The last unsupported security release for 4.4.4 was *over a year ago*: https://source.android.com/security/bulletin/2017-10-01.
