### ISSUE TITLE
Adding better support for dagger 2

### ISSUE THREAD

**Issue by Vahalaru** [kittinunf/Fuel#492]
Idk if the is anything you can do to improve dagger 2 support code wise.  If anything could you provide an example of how to use in the read me.

**Comment by iNoles** [comment]
I think dagger 2 is out of the scope of this project.

**Comment by Vahalaru** [comment]
Well the reason I brought it up was I'm using this tutorial to build my app using the new mvvm.

https://proandroiddev.com/mvvm-with-kotlin-android-architecture-components-dagger-2-retrofit-and-rxandroid-1a4ebb38c699

I have to say I've had the best of luck with using the Fuel library out of them all. I had started to try and piece by piece replace the necessary parts from retrofit to Fuel, and got to thinking that I was having a hard enough time understanding how everything went together some guidance on the conversion would relieve a few headaches. The main part that I'm iffy on is towards the very end where he does the subscribe then checks if there is any data stored in the local doa if not request for data and then store in the doa. It's also using live data so there is a lot going on. 
Thanks for your time.

**Comment by SleeplessByte** [comment]
Replace `NetworkModule`  with something like this:

```kotlin
/**
 * Module which provides all required dependencies about network
 */
@Module
// Safe here as we are dealing with a Dagger 2 module
@Suppress("unused")
object NetworkModule {
    /**
     * Provides the FuelManager
     * @return the FuelManager
     */
    @Provides
    @Reusable
    @JvmStatic
    internal fun provideFuelManager(): FuelManager {
        return FuelManager(basePath = BASE_URL)
    }
}
```

- There are no adapters in `Fuel`, only extension methods
- `basePath` is both `baseUrl` and path
- There are no "post" api classes/objects/interfaces, only a method to make a post api

Yes, there is a way to mimic `postApi` and the retrofit interfaces with `FuelRouting`, but you can add that after you understand this example. Just want to keep it simple for now.

Replace all instances of `PostApi` with `FuelManager`
```kotlin
class PostListViewModel:BaseViewModel(){
    @Inject
    lateinit var fuelManager: FuelManager
}
```

Replace the `subscription = postApi.getPosts()` line with an actual call to get the posts. You can use the `Rx` extensions, for example `rx_response`.

```kotlin
  fuelManager.post("path").rx_response()
    ...
```

As you can see, there is no specific "Dagger 2 🗡 " - `Fuel` code, because none of the changes I've shown above have anything to do with specifics between these two. When you have this working, you can implement `FuelRouting` to get a similar `getPosts()` call.

I'm now closing ❌ this issue. We welcome documentation in the form of a Wiki post once you're done, and I suggest further help via Slack or Stack Overflow.

**Comment by Vahalaru** [comment]
Thank you,  this will work with the methodology of seperating the code and be a simple workable solution. I was overthinking it. When I get it all worked out I'll sue post a wiki documentation.

**Comment by SleeplessByte** [comment]
Perfect!
