### ISSUE TITLE
Be able to control redirect behavior per quest / bring cookies when redirect

### ISSUE THREAD

**Issue by wusatosi** [kittinunf/Fuel#514]
# Feature Request

## Description
I'm using Fuel as my http client to simulate login on a site as an auto script, where I found the short of unable to control redirect behavior a bit awkward, since Fuel.get / post is stateless, which do not have cookie management built in, when I sign in, server sends back an 302 redirect, fuel follows redirect and sent a new request, but did not bring cookies with it, which gets 302 redirect because it's unauthorized, in the end I land back on the login page again, making three request pointless and unusable without the remove all interceptor hack.

![image](https://user-images.githubusercontent.com/26424577/48194837-0f35aa00-e389-11e8-8030-de5ea1442d61.png)

## Proposed Solution
As #104 suggests, 
```kotlin
Fuel.get(url)    // Follows redirects (behaviour unchanged).
Fuel.get(url, follow = true)     // Explicitly follow redirects.
Fuel.get(url, follow = false)    // Does not follow redirects.
```
or
````kotlin
Fuel
    .get(url)
    .followRedirect(false) //disable redirect
````
or even
````kotlin
Fuel.get(url, fowardCookieWhenRedirect = true) // process cookie from Set-cookie / Set-cookie2 and forward to next request
````

## Alternatives I've considered
```kotlin
Fuel.get(url, redirectHandler = { request, response  -> /**
  epic magic that returns an request config or null to stop redirection
*/ }
```

## Additional context
Nop

**Comment by SleeplessByte** [comment]
Hi there!

In the current `master` and released versions, the redirection you ask for is available through [allowRedirects](https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Request.kt#L425)

```kotlin
request.allowRedirects(false)

// For example
Fuel.get(url).allowRedirects(false)
```
Please note that this will act as an "error", but as long as you use a `Result`, you can then inspect the `response[Headers.LOCATION]` and handle the request yourself.

Your other request is handled by #263 (and #105, #458), which are coming after [version 2.0.0](https://github.com/kittinunf/Fuel/milestone/3).

Since this is a duplicate I am closing this issue, but feel free to respond here!

**Comment by wusatosi** [comment]
Thanks for reply, throwing an exception is understandable here. just remember to write `.allowRedirects` into documentations and examples.
Thanks!

**Comment by SleeplessByte** [comment]
@wusatosi you are absolutely right. We are updating the docs for 2.0.0 <3

**Comment by wusatosi** [comment]
Thanks for the excellent support! loving your work!

**Comment by wusatosi** [comment]
Oh bug report on the redirect part, when redirected, the Response object returned did not fulfill any information about the actual response, nor the response header and the statues code (which is -1) is not empty value.
![image](https://user-images.githubusercontent.com/26424577/49207753-d2415e00-f3f0-11e8-8880-0424489233cd.png)

@SleeplessByte

**Comment by SleeplessByte** [comment]
In 2.0.0 (master branch) response errors should have full response values.

For now you I think the bug is that you still need to add 300...399 as valid status in order to be able to get the whole response, but I'm not sure of the top of my head. You do this by removing all the interceptors first and then adding back validStatusInterceptor(100...399).

**Comment by SleeplessByte** [comment]
The response variable should not be affected by the validStatusInterceptor
interceptor, so your comment is on point! Also has been fixed in master :)
