### ISSUE TITLE
Support - SDK 15

### ISSUE THREAD

**Issue by miguelpimentel** [kittinunf/fuel#619]
# Feature Request

## Description
Support starting in Android SDK 15

## Alternatives I've considered
Currently, Im working with an old system, that supports user with SDK 15. I'm facing off to fix bugs with Retrofit in their current version. So, I decided to test Fuel, I've had a great experience before with it. But unfortunately, It's only available for SDK 19 or higher. Is there any Fuel Version that supports 15?

**Comment by SleeplessByte** [comment]
The reasonable [minSDK](https://twitter.com/minSdkVersion) has been [16](https://twitter.com/minSdkVersion/status/629094431031980032) since mid 2015 and [19](https://twitter.com/minSdkVersion/status/795702388774567936) since november 2016. We should _actually_ increase the min SDK to [21](https://twitter.com/minSdkVersion/status/988538738639765505).

**Comment by miguelpimentel** [comment]
Thanks for the support. I'm working with a huge app with more than 500k user, I was thinking in switch from volley to Fuel, but we have to support a few number of users in SKD 15.

**Comment by iNoles** [comment]
You could use Kotlin coroutines android for it that able to support much older min SDK.
