### ISSUE TITLE
Add support OkHttp library

### ISSUE THREAD

**Issue by lenguyenthanh** [kittinunf/Fuel#98]
As OkHttp has many advantages and there a lot of Android applications already use OkHttp. Should this library supports OkHttp as a plugin or uses it directly?

**Comment by yoavst** [comment]
In order to do that, you need to create a [Client](https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/Client.kt) that uses `OkHttp`.

Here is the default client: [`HttpClient`](https://github.com/kittinunf/Fuel/blob/master/fuel/src/main/kotlin/com/github/kittinunf/fuel/toolbox/HttpClient.kt)

**Comment by lenguyenthanh** [comment]
So should we create a library call fuel-okhttp in this repository?

**Comment by kittinunf** [comment]
I think it should be separated. You could open up with your repo that supports OkHttp. I am happy to link it in readme of this repo.
